import {v4 as uuid} from "uuid";

/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
    {
        _id: uuid(),
        title: "Avatar: The Way of Water (2022)",
        thumbnail: 'https://i.postimg.cc/c4QhXLdF/avatar1.jpg',
        videoLink: "https://youtube.com/embed/wcMqHWEJBgg",
        description: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
        likes: false,
        dislikes: false,
        dateOfPost: 'Dec 14, 2022',
        rating: '4.2',
        genre: 'Science Fiction',
        comments: [{user: 'rahul', message: 'very interesting movie, i loved it.'}],
        language: 'Hindi',
        duration: '3h 12m',
        director: 'James Cameron'
    },
    {
        _id: uuid(),
        title: "Ant-Man and the Wasp: Quantumania",
        thumbnail: 'https://i.postimg.cc/ZR8nX20z/quantumania1.jpg',
        videoLink: "https://youtube.com/embed/nYzlbXWHGJU",
        description: "Scott Lang and Hope Van Dyne are dragged into the Quantum Realm, along with Hope's parents and Scott's daughter Cassie. Together they must find a way to escape, but what secrets is Hope's mother hiding? And who is the mysterious Kang?",
        likes: false,
        dislikes: false,
        dateOfPost: 'Apr 19, 2023',
        rating: '6.1',
        genre: 'Science Fiction',
        comments: [{user: 'rahul', message: 'very interesting movie, i loved it.'}],
        language: 'Hindi',
        duration: '2h 4m',
        director: 'Peyton Reed'
    },
    {
        _id: uuid(),
        title: "Guardians of the Galaxy Vol. 3",
        thumbnail: 'https://i.postimg.cc/HkYwz0ZL/gardian-of-galaxy.jpg',
        videoLink: "https://youtube.com/embed/fRL9UiVp_nk",
        description: "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.",
        likes: false,
        dislikes: false,
        dateOfPost: 'May 03, 2023',
        rating: '4.3',
        genre: 'Science Fiction',
        comments: [{user: 'rahul', message: 'very interesting movie, i loved it.'}],
        language: 'Hindi',
        duration: '2h 30m',
        director: 'James Gunn'
    },
    {
        _id: uuid(),
        title: "Transformers: Rise of the Beasts",
        thumbnail: 'https://i.postimg.cc/fb4wZCGz/transformers.jpg',
        videoLink: "https://youtube.com/embed/IUhu2iHZqaY",
        description: "A '90s globetrotting adventure that introduces the Maximals, Predacons, and Terrorcons to the existing battle on earth between Autobots and Decepticons.",
        liked: false,
        disliked: true,
        dateOfPost: 'Jun 06, 2023',
        rating: '7.4',
        genre: 'Science Fiction',
        comments: [{user: 'rahul', message: 'very interesting movie, i loved it.'}],
        language: 'Hindi',
        duration: '2h 7m',
        director: 'Steven Caple Jr.'
    },
    {
        _id: uuid(),
        title: "Godzilla vs. Kong",
        thumbnail: 'https://i.postimg.cc/43MpXDJK/godzilla-vs-cong.jpg',
        videoLink: "https://youtube.com/embed/IvTuXTMUHik",
        description: "The epic next chapter in the cinematic Monsterverse pits two of the greatest icons in motion picture history against each other--the fearsome Godzilla and the mighty Kong--with humanity caught in the balance.",
        likes: false,
        dislikes: false,
        dateOfPost: 'March 24, 2021',
        rating: '6.3',
        genre: 'Action',
        comments: [{user: 'rahul', message: 'very interesting movie, i loved it.'}],
        language: 'Hindi',
        duration: '1h 53m',
        director: 'Adam Wingard'
    },
    {
        _id: uuid(),
        title: "Spider-Man: No Way Home",
        thumbnail: 'https://i.postimg.cc/y8Dd7kWP/spiderman-no-way-home.jpg',
        videoLink: "https://youtube.com/embed/GUQdGyBjRU0",
        description: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
        likes: false,
        dislikes: false,
        dateOfPost: 'Dec 16, 2021',
        rating: '8.2',
        genre: 'Adventure',
        comments: [{user: 'rahul', message: 'very interesting movie, i loved it.'}],
        language: 'Hindi',
        duration: '2h 28m',
        director: 'Jon Watts'
    },
    {
        _id: uuid(),
        title: "Guardians of the Galaxy Vol. 2",
        thumbnail: 'https://i.postimg.cc/2S04KqM7/gardian-of-galaxy-vol2.jpg',
        videoLink: "https://youtube.com/embed/IIsaipJTT4E",
        description: "The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord's encounter with his father, the ambitious celestial being Ego.",
        likes: false,
        dislikes: false,
        dateOfPost: 'Apr 19, 2017',
        rating: '7.6',
        genre: 'Adventure',
        comments: [{user: 'rahul', message: 'very interesting movie, i loved it.'}],
        language: 'Hindi',
        duration: '2h 16m',
        director: 'James Gunn'
    },
    {
        _id: uuid(),
        title: "Thor: Love and Thunder",
        thumbnail: 'https://i.postimg.cc/yYd6TkhH/thor-love-and-thunder.jpg',
        videoLink: "https://youtube.com/embed/sFTD5vBfRGY",
        description: "Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster to fight Gorr the God Butcher, who intends to make the gods extinct.",
        likes: false,
        dislikes: false,
        dateOfPost: 'Jul 06, 2022',
        rating: '6.2',
        genre: 'Adventure',
        comments: [{user: 'rahul', message: 'very interesting movie, i loved it.'}],
        language: 'Hindi',
        duration: '1h 58m',
        director: 'Taika Waititi'
    },
    {
        _id: uuid(),
        title: "Knights of the Zodiac",
        thumbnail: 'https://i.postimg.cc/jS2WCM3y/knights-of-the-zodiac.jpg',
        videoLink: "https://youtube.com/embed/Sko0o_KoBHY",
        description: "When a goddess of war reincarnates in the body of a young girl, street orphan Seiya discovers that he is destined to protect her and save the world. But only if he can face his own past and become a Knight of the Zodiac.",
        likes: false,
        dislikes: false,
        dateOfPost: 'Apr 27, 2023',
        rating: '4.5',
        genre: 'Adventure',
        comments: [{user: 'rahul', message: 'very interesting movie, i loved it.'}],
        language: 'English',
        duration: '1h 52m',
        director: 'Tomasz Baginski'
    },
    {
        _id: uuid(),
        title: "Doctor Strange in the Multiverse of Madness",
        thumbnail: 'https://i.postimg.cc/HWM9kk8T/dr-strange-multiverse.jpg',
        videoLink: "https://youtube.com/embed/-mjWrrKgwJM",
        description: "Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself, which threaten to wipe out millions across the multiverse. They seek help from Wanda the Scarlet Witch, Wong and others.",
        likes: false,
        dislikes: false,
        dateOfPost: 'May 04, 2022',
        rating: '6.9',
        genre: 'Adventure',
        comments: [{user: 'rahul', message: 'very interesting movie, i loved it.'}],
        language: 'Hindi',
        duration: '2h 6m',
        director: 'Sam Raimi'
    },
    {
        _id: uuid(),
        title: "Avengers: Infinity War",
        thumbnail: 'https://i.postimg.cc/ydgX9VfX/avengers-infinity-war.jpg',
        videoLink: "https://youtube.com/embed/twXfolLOiHc",
        description: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
        likes: false,
        dislikes: false,
        dateOfPost: 'Apr 23, 2018',
        rating: '8.4',
        genre: 'Science Fiction',
        comments: [{user: 'rahul', message: 'very interesting movie, i loved it.'}],
        language: 'Hindi',
        duration: '2h 29m',
        director: 'Anthony Russo, Joe Russo'
    },
    {
        _id: uuid(),
        title: "Harry Potter and the Deathly Hallows: Part 2",
        thumbnail: 'https://i.postimg.cc/qR3yq1R1/harry-potter-and-deathly-hallow.jpg',
        videoLink: "https://youtube.com/embed/mObK5XD8udk",
        description: "Harry, Ron, and Hermione search for Voldemort's remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages on at Hogwarts.",
        likes: false,
        dislikes: false,
        dateOfPost: 'Jul 7, 2011',
        rating: '8.1',
        genre: 'Adventure',
        comments: [{user: 'rahul', message: 'very interesting movie, i loved it.'}],
        language: 'Hindi',
        duration: '2h 10m',
        director: 'David Yates'
    },
    {
        _id: uuid(),
        title: "Harry Potter and the Goblet of Fire",
        thumbnail: 'https://i.postimg.cc/PJnZw1vT/harry-potter-and-goblet.jpg',
        videoLink: "https://youtube.com/embed/3EGojp4Hh6I",
        description: "Harry Potter finds himself competing in a hazardous tournament between rival schools of magic, but he is distracted by recurring nightmares.",
        likes: false,
        dislikes: false,
        dateOfPost: 'Nov 06, 2005',
        rating: '7.7',
        genre: 'Adventure',
        comments: [{user: 'rahul', message: 'very interesting movie, i loved it.'}],
        language: 'English',
        duration: '2h 37m',
        director: 'Mike Newell'
    },
    {
        _id: uuid(),
        title: "Interstellar",
        thumbnail: 'https://i.postimg.cc/Yq3gvGrB/intersteller1.jpg',
        videoLink: "https://youtube.com/embed/4REFMXawFEA",
        description: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
        likes: false,
        dislikes: false,
        dateOfPost: 'Oct 26, 2014',
        rating: '8.7',
        genre: 'Science Fiction',
        comments: [{user: 'rahul', message: 'very interesting movie, i loved it.'}],
        language: 'Hindi',
        duration: '2h 49m',
        director: 'Christopher Nolan'
    },
    {
        _id: uuid(),
        title: "Justice League",
        thumbnail: 'https://i.postimg.cc/0jvMQxhN/justice-league.jpg',
        videoLink: "https://youtube.com/embed/9Wly6N7dSkM",
        description: "Fueled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne enlists the help of his new-found ally, Diana Prince, to face an even greater enemy.",
        likes: false,
        dislikes: false,
        dateOfPost: 'Nov 13, 2017',
        rating: '6.1',
        genre: 'Adventure',
        comments: [{user: 'rahul', message: 'very interesting movie, i loved it.'}],
        language: 'Hindi',
        duration: '2h',
        director: 'Zack Snyder'
    }
];
